//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PostViewerTool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PostViewerTool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://jsonplaceholder.typicode.com/posts.
        /// </summary>
        internal static string Application_JsonwebApiurlstring {
            get {
                return ResourceManager.GetString("Application_JsonwebApiurlstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Post Viewer Tool V 1.0.
        /// </summary>
        internal static string Application_titlestring {
            get {
                return ResourceManager.GetString("Application_titlestring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote server has thrown an internal error. Url &apos;http://jsonplaceholder.typicode.com/posts&apos; is not valid or forbidden access.
        /// </summary>
        internal static string ExceptionMessage_AccessdeniedInvalidURLstring {
            get {
                return ResourceManager.GetString("ExceptionMessage_AccessdeniedInvalidURLstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid JSON content.
        /// </summary>
        internal static string ExceptionMessage_InvalidJSON_Data {
            get {
                return ResourceManager.GetString("ExceptionMessage_InvalidJSON_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xsl:stylesheet version=&quot;1.0&quot; xmlns:xsl=&quot;http://www.w3.org/1999/XSL/Transform&quot; xmlns:msxsl=&quot;urn:schemas-microsoft-com:xslt&quot; exclude-result-prefixes=&quot;msxsl&quot;&gt;
        ///  &lt;xsl:output method=&quot;html&quot; /&gt;
        ///  &lt;xsl:template match=&quot;/&quot;&gt;
        ///    &lt;html&gt;
        ///      &lt;head&gt;
        ///        &lt;script type=&quot;text/css&quot;&gt;
        ///          body
        ///          {
        ///          font-family:perpetua, Arial, san-serif;
        ///          font-size:5;
        ///          }
        ///        &lt;/script&gt;
        ///      &lt;/head&gt;
        ///      &lt;body&gt;
        ///        &lt;table border=&quot;1&quot;&gt;
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HtmlParser {
            get {
                return ResourceManager.GetString("HtmlParser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;body&quot;: &quot;eveniet quo quis laborum totam consequatur non dolor ut et est repudiandae est voluptatem vel debitis et magnam&quot;.
        /// </summary>
        internal static string Post_bodystring {
            get {
                return ResourceManager.GetString("Post_bodystring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;id&quot;: 18,.
        /// </summary>
        internal static string Post_postidstring {
            get {
                return ResourceManager.GetString("Post_postidstring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;title&quot;: &quot;voluptate et itaque vero tempora molestiae&quot;,.
        /// </summary>
        internal static string Post_Titlestring {
            get {
                return ResourceManager.GetString("Post_Titlestring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Id = &apos;{0}&apos; and Post Id = &apos;{1}&apos; {2}Title = &apos;{3}&apos; {4}Body = &apos;{5}&apos;.
        /// </summary>
        internal static string Post_Tostring {
            get {
                return ResourceManager.GetString("Post_Tostring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;userId&quot;: 2,.
        /// </summary>
        internal static string Post_UserIdstring {
            get {
                return ResourceManager.GetString("Post_UserIdstring", resourceCulture);
            }
        }
    }
}
